# Standalone compose with embedded MongoDB (for testing)
services:
  # Single container with embedded MongoDB
  claw-standalone:
    build:
      context: .
      dockerfile: Dockerfile.standalone
    container_name: claw-standalone
    restart: unless-stopped
    ports:
      - "8000:8000"   # API
      - "27017:27017" # MongoDB (for external access)
    environment:
      NODE_ENV: development
      PORT: 8000
      HOST: 0.0.0.0
      MONGODB_URL: mongodb://localhost:27017/claw_api
      DB_NAME: claw_api
      WORKSPACE_DIR: /app/workspace
      
      # LLM API Keys
      HUGGINGFACE_API_KEY: ${HUGGINGFACE_API_KEY:-}
      GROQ_API_KEY: ${GROQ_API_KEY:-}
    volumes:
      - ./src:/app/src:ro
      - ./logs:/app/logs
      - workspace_data:/app/workspace
      - mongodb_standalone_data:/data/db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  workspace_data:
  mongodb_standalone_data:
