version: '3.8'

services:
  # MongoDB database
  mongodb:
    image: mongo:7.0
    container_name: v0-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: v0_clone
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - v0-network

  # Redis for caching (optional)
  redis:
    image: redis:7-alpine
    container_name: v0-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - v0-network

  # Main API application
  api:
    build: .
    container_name: v0-api
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      NODE_ENV: production
      PORT: 8000
      HOST: 0.0.0.0
      MONGODB_URL: mongodb://admin:password123@mongodb:27017/v0_clone?authSource=admin
      DB_NAME: v0_clone
      WORKSPACE_DIR: /app/workspace
      
      # LLM API Keys (set these in your environment)
      HUGGINGFACE_API_KEY: ${HUGGINGFACE_API_KEY}
      GROQ_API_KEY: ${GROQ_API_KEY}
      OLLAMA_URL: http://ollama:11434
      
      # Redis URL
      REDIS_URL: redis://redis:6379
    volumes:
      - workspace_data:/app/workspace
      - ./logs:/app/logs
    depends_on:
      - mongodb
      - redis
    networks:
      - v0-network

  # Ollama for local LLM (optional)
  ollama:
    image: ollama/ollama:latest
    container_name: v0-ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - v0-network
    # Uncomment if you have GPU support
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]

  # Nginx reverse proxy (optional)
  nginx:
    image: nginx:alpine
    container_name: v0-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - api
    networks:
      - v0-network

volumes:
  mongodb_data:
  redis_data:
  ollama_data:
  workspace_data:

networks:
  v0-network:
    driver: bridge
