services:
  # MongoDB database
  mongodb:
    image: mongo:7.0
    container_name: claw-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: claw_api
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - claw-network

  # Claw API
  api:
    build: .
    container_name: claw-api
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      NODE_ENV: production
      PORT: 8000
      MONGODB_URL: mongodb://admin:password123@mongodb:27017/claw_api?authSource=admin
      DB_NAME: claw_api
      EXTERNAL_GAME_API_URL: ${EXTERNAL_GAME_API_URL:-http://localhost:3001}
      JWT_SECRET: ${JWT_SECRET:-your-super-secret-jwt-key}
    depends_on:
      - mongodb
    networks:
      - claw-network

volumes:
  mongodb_data:

networks:
  claw-network:
    driver: bridge
